# Site settings
title: Tobbyn
email: z85146549@163.com
description: 修行就是该干嘛干嘛，好好吃饭，好好睡觉，认真做事，和周围的人开开心心，然后有一份好的收入️
# the subpath of your site, e.g. /blog/
baseurl: ""
# the base hostname & protocol for your site
url: "http://243654.top"
#twitter_username: jekyllrb
github_username:  zhhb

# Build settings
markdown: kramdown
